resources:
  pipelines:
    healthcare_dlt_pipeline:
      name: healthcare_dlt_pipeline_${bundle.target}
      catalog: health_care
      schema: ${var.target_schema}
      serverless: true

      libraries:
        - file:
            path: ../src/bronze.py
        - file:
            path: ../src/silver.py
        - file:
            path: ../src/gold.py
